DELETE FROM bookings;
ALTER TABLE bookings ALTER COLUMN ID RESTART WITH 1;
DELETE FROM comments;
ALTER TABLE comments ALTER COLUMN ID RESTART WITH 1;
DELETE FROM users;
ALTER TABLE users ALTER COLUMN ID RESTART WITH 1;
DELETE FROM items;
ALTER TABLE items ALTER COLUMN ID RESTART WITH 1;